import type { User, Impact, Recognition, CAF, Notification, Infraction } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const mockUsers: User[] = [
  {
    uid: 'user-teammate-1',
    email: 'teammate1@example.com',
    displayName: 'Alex Ray',
    role: 'teammate',
    supervisorId: 'user-supervisor-1',
    location: 'STORE-001',
    photoURL: PlaceHolderImages.find(img => img.id === 'user-1')?.imageUrl,
    isActive: true,
    metadata: { createdAt: new Date(), updatedAt: new Date() },
  },
  {
    uid: 'user-supervisor-1',
    email: 'supervisor1@example.com',
    displayName: 'Jordan Lee',
    role: 'supervisor',
    supervisorId: 'user-admin-1',
    location: 'STORE-001',
    photoURL: PlaceHolderImages.find(img => img.id === 'user-2')?.imageUrl,
    isActive: true,
    metadata: { createdAt: new Date(), updatedAt: new Date() },
  },
  {
    uid: 'user-teammate-2',
    email: 'teammate2@example.com',
    displayName: 'Casey Jordan',
    role: 'teammate',
    supervisorId: 'user-supervisor-1',
    location: 'STORE-001',
    photoURL: PlaceHolderImages.find(img => img.id === 'user-3')?.imageUrl,
    isActive: true,
    metadata: { createdAt: new Date(), updatedAt: new Date() },
  },
   {
    uid: 'user-lead-1',
    email: 'lead1@example.com',
    displayName: 'Taylor Morgan',
    role: 'lead',
    supervisorId: 'user-supervisor-1',
    location: 'STORE-001',
    photoURL: PlaceHolderImages.find(img => img.id === 'user-4')?.imageUrl,
    isActive: true,
    metadata: { createdAt: new Date(), updatedAt: new Date() },
  },
];

export const mockImpacts: Impact[] = [
  {
    id: 'impact-1',
    userId: 'user-teammate-1',
    userName: 'Alex Ray',
    supervisorId: 'user-supervisor-1',
    shiftDate: '2024-07-20',
    reason: 'SICK',
    details: 'Feeling unwell, flu-like symptoms.',
    status: 'SUBMITTED',
    reportedBy: 'user-teammate-1',
    method: 'APP',
    history: [],
    createdAt: new Date('2024-07-20T06:00:00Z'),
  },
  {
    id: 'impact-2',
    userId: 'user-teammate-2',
    userName: 'Casey Jordan',
    supervisorId: 'user-supervisor-1',
    shiftDate: '2024-07-21',
    reason: 'LATE',
    details: 'Stuck in traffic, will be 15 minutes late.',
    status: 'SUBMITTED',
    reportedBy: 'user-teammate-2',
    method: 'TEXT',
    history: [],
    createdAt: new Date('2024-07-21T08:45:00Z'),
  },
  {
    id: 'impact-3',
    userId: 'user-teammate-1',
    userName: 'Alex Ray',
    supervisorId: 'user-supervisor-1',
    shiftDate: '2024-07-15',
    reason: 'EMERGENCY',
    details: 'Family emergency, need to leave immediately.',
    status: 'EXCUSED',
    reportedBy: 'user-supervisor-1',
    method: 'PHONE',
    history: [],
    createdAt: new Date('2024-07-15T14:00:00Z'),
  },
];

export const mockRecognitions: Recognition[] = [
  {
    id: 'rec-1',
    userId: 'user-teammate-1',
    submittedByUid: 'user-supervisor-1',
    category: 'CUSTOMER_SERVICE',
    tier: 'WRITTEN',
    description: 'Alex received a glowing review from a customer for going above and beyond to help them find a product.',
    isApproved: true,
    approvedByUid: 'user-supervisor-1',
    approvedAt: new Date(),
    createdAt: new Date('2024-07-19T10:00:00Z'),
  },
  {
    id: 'rec-2',
    userId: 'user-teammate-2',
    submittedByUid: 'user-lead-1',
    category: 'TEAMWORK',
    tier: 'VERBAL',
    description: 'Casey stayed late to help the closing team catch up after a busy day. Great team player!',
    isApproved: false,
    createdAt: new Date('2024-07-22T09:00:00Z'),
  },
];

export const mockCAFs: CAF[] = [
  {
    id: 'caf-1',
    userId: 'user-teammate-1',
    supervisorId: 'user-supervisor-1',
    status: 'PENDING_ASSOCIATE_SIG',
    subject: 'Attendance Policy Violation',
    policyText: 'Per company policy, unexcused absences are subject to corrective action...',
    specificDetails: 'Alex had a No-Call-No-Show on 2024-07-18.',
    requiredImprovement: 'Must adhere to call-out procedures for all future absences.',
    supervisorSignatureUrl: '',
    supervisorSignedAt: new Date('2024-07-19T11:00:00Z'),
    linkedInfractionIds: ['inf-1'],
    createdAt: new Date('2024-07-19T11:00:00Z'),
  },
];

export const mockInfractions: Infraction[] = [
  {
    id: 'inf-1',
    userId: 'user-teammate-1',
    reportedByUid: 'user-supervisor-1',
    type: 'NO_CALL_NO_SHOW',
    occurredAt: new Date('2024-07-18T09:00:00Z'),
    details: 'Did not show up for scheduled shift and did not contact leadership.',
    status: 'CAF_CREATED',
    linkedCafId: 'caf-1',
    location: 'STORE-001',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    recipientUid: 'user-supervisor-1',
    type: 'PATTERN_ALERT',
    message: 'Alex Ray has 3 unexcused impacts in the last 30 days.',
    linkPath: '/team/user-teammate-1',
    read: false,
    createdAt: new Date('2024-07-21T10:00:00Z'),
  },
  {
    id: 'notif-2',
    recipientUid: 'user-supervisor-1',
    type: 'PATTERN_ALERT',
    message: 'Casey Jordan has 2 Late Arrivals in the last 30 days.',
    linkPath: '/team/user-teammate-2',
    read: true,
    createdAt: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: 'notif-3',
    recipientUid: 'user-teammate-1',
    type: 'SIGNATURE_REQ',
    message: 'You have a Corrective Action Form requiring your signature.',
    linkPath: '/caf/caf-1',
    read: false,
    createdAt: new Date('2024-07-19T11:05:00Z'),
  },
];
